// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDx1xNnd9pXlgiXOjGM7x5iprjnqZTMaSU',
    appId: '1:903476823818:web:81a6a7ee3519ecffc85cf3',
    messagingSenderId: '903476823818',
    projectId: 'referral-application-32d87',
    authDomain: 'referral-application-32d87.firebaseapp.com',
    storageBucket: 'referral-application-32d87.appspot.com',
    measurementId: 'G-P6Y14ZY68L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6JNBid5m7xJEYisNehzaW9k8ODLh2_34',
    appId: '1:903476823818:android:3e0ebdd351b7c037c85cf3',
    messagingSenderId: '903476823818',
    projectId: 'referral-application-32d87',
    storageBucket: 'referral-application-32d87.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBo5WbOrgJ9RskCb3NejPyaOQau7l4IqaA',
    appId: '1:903476823818:ios:c84b242d52244d1cc85cf3',
    messagingSenderId: '903476823818',
    projectId: 'referral-application-32d87',
    storageBucket: 'referral-application-32d87.appspot.com',
    iosClientId: '903476823818-a9p4eg7br5fu3sjumqgnp1t7htb44vtc.apps.googleusercontent.com',
    iosBundleId: 'com.example.referralApp',
  );
}
